name: UI Automated Tests

on:
  push:
    branches: [ "main", "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: 1. 拉取代码
      uses: actions/checkout@v4

    - name: 2. 配置 Python 环境 (3.13)
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: 3. 安装依赖包
      run: |
        python -m pip install --upgrade pip
        pip install -r Project1/requirements.txt

    - name: 4. 运行自动化测试
      run: |
        pytest Project1/test_case2.py -s --alluredir=./allure-results

    - name: 5. 存档测试报告 (Artifacts)
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: allure-results
        path: ./allure-results