name: UI Automated Tests

on:
  push:
    branches: [ "main", "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: 1. 拉取代码
      uses: actions/checkout@v4

    - name: 2. 配置 Python 环境 (3.13)
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: 3. 安装依赖包
      run: |
        python -m pip install --upgrade pip
        pip install -r Project1/requirements.txt

    - name: 4. 运行自动化测试
      run: |
        pytest Project1/test_case2.py -s --alluredir=./allure-results

    - name: 5. 获取历史测试数据 (为了画出帅气的趋势图)
      uses: actions/checkout@v4
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    - name: 6. 报告加工厂：生成 Allure 网页
      uses: simple-elf/allure-report-action@v1.14
      if: always()
      with:
        allure_results: allure-results
        gh_pages: gh-pages
        allure_report: allure-report
        allure_history: allure-history

    - name: 7. 快递员：一键发布到 GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: allure-history

